//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQLCHDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIETHD = new HashSet<CHITIETHD>();
            this.KHO_SANPHAM = new HashSet<KHO_SANPHAM>();
        }
    
        public int MAHD { get; set; }
        public Nullable<System.DateTime> NGAYBAN { get; set; }
        public Nullable<System.DateTime> NGAYTHANHTOAN { get; set; }
        public Nullable<decimal> GIAMGIA { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public string GHICHU { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<int> MANV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHD> CHITIETHD { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHO_SANPHAM> KHO_SANPHAM { get; set; }
    }
}
