//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQLCHDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.HOADON = new HashSet<HOADON>();
        }
    
        public int MAKH { get; set; }
        public string TENKH { get; set; }
        public string GIOITINH { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAI { get; set; }
        public string LOAIKH { get; set; }
        public Nullable<int> IDTK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADON { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
