//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQLCHDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO_SANPHAM
    {
        public int MASP { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
        public Nullable<int> MAPN { get; set; }
        public Nullable<int> MAHD { get; set; }
        public System.DateTime NGAYCAPNHAT { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
