//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQLCHDT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLY_SHOPDTDD1Entities : DbContext
    {
        public QLY_SHOPDTDD1Entities()
            : base("name=QLY_SHOPDTDD1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOPHANKHO> BOPHANKHO { get; set; }
        public virtual DbSet<CHITIETHD> CHITIETHD { get; set; }
        public virtual DbSet<CHITIETPN> CHITIETPN { get; set; }
        public virtual DbSet<HOADON> HOADON { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANG { get; set; }
        public virtual DbSet<KHO_SANPHAM> KHO_SANPHAM { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAP { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
        public virtual DbSet<PHANQUYEN> PHANQUYEN { get; set; }
        public virtual DbSet<PHIEUNHAP> PHIEUNHAP { get; set; }
        public virtual DbSet<SANPHAM> SANPHAM { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOAN { get; set; }
        public virtual DbSet<THUONGHIEU> THUONGHIEU { get; set; }
    
        public virtual int sp_CapNhatQuyen(Nullable<int> mANV, Nullable<bool> qL_DONHANG, Nullable<bool> qL_SANPHAM, Nullable<bool> qL_KHACHHANG, Nullable<bool> qL_NHANVIEN, Nullable<bool> qL_NHACC, Nullable<bool> qL_NHAPHANG, Nullable<bool> qL_BPKHO, Nullable<bool> tHONGKE)
        {
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            var qL_DONHANGParameter = qL_DONHANG.HasValue ?
                new ObjectParameter("QL_DONHANG", qL_DONHANG) :
                new ObjectParameter("QL_DONHANG", typeof(bool));
    
            var qL_SANPHAMParameter = qL_SANPHAM.HasValue ?
                new ObjectParameter("QL_SANPHAM", qL_SANPHAM) :
                new ObjectParameter("QL_SANPHAM", typeof(bool));
    
            var qL_KHACHHANGParameter = qL_KHACHHANG.HasValue ?
                new ObjectParameter("QL_KHACHHANG", qL_KHACHHANG) :
                new ObjectParameter("QL_KHACHHANG", typeof(bool));
    
            var qL_NHANVIENParameter = qL_NHANVIEN.HasValue ?
                new ObjectParameter("QL_NHANVIEN", qL_NHANVIEN) :
                new ObjectParameter("QL_NHANVIEN", typeof(bool));
    
            var qL_NHACCParameter = qL_NHACC.HasValue ?
                new ObjectParameter("QL_NHACC", qL_NHACC) :
                new ObjectParameter("QL_NHACC", typeof(bool));
    
            var qL_NHAPHANGParameter = qL_NHAPHANG.HasValue ?
                new ObjectParameter("QL_NHAPHANG", qL_NHAPHANG) :
                new ObjectParameter("QL_NHAPHANG", typeof(bool));
    
            var qL_BPKHOParameter = qL_BPKHO.HasValue ?
                new ObjectParameter("QL_BPKHO", qL_BPKHO) :
                new ObjectParameter("QL_BPKHO", typeof(bool));
    
            var tHONGKEParameter = tHONGKE.HasValue ?
                new ObjectParameter("THONGKE", tHONGKE) :
                new ObjectParameter("THONGKE", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatQuyen", mANVParameter, qL_DONHANGParameter, qL_SANPHAMParameter, qL_KHACHHANGParameter, qL_NHANVIENParameter, qL_NHACCParameter, qL_NHAPHANGParameter, qL_BPKHOParameter, tHONGKEParameter);
        }
    
        public virtual int sp_DuyetDonHang(Nullable<int> mAHD)
        {
            var mAHDParameter = mAHD.HasValue ?
                new ObjectParameter("MAHD", mAHD) :
                new ObjectParameter("MAHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DuyetDonHang", mAHDParameter);
        }
    
        public virtual int sp_LapChiTietHoaDon(Nullable<int> mAHD, Nullable<int> mASP, Nullable<int> sOLUONG)
        {
            var mAHDParameter = mAHD.HasValue ?
                new ObjectParameter("MAHD", mAHD) :
                new ObjectParameter("MAHD", typeof(int));
    
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            var sOLUONGParameter = sOLUONG.HasValue ?
                new ObjectParameter("SOLUONG", sOLUONG) :
                new ObjectParameter("SOLUONG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LapChiTietHoaDon", mAHDParameter, mASPParameter, sOLUONGParameter);
        }
    
        public virtual int sp_LapChiTietPhieuNhap(Nullable<int> mAPN, Nullable<int> mASP, Nullable<int> sOLUONG, Nullable<decimal> gIANHAP)
        {
            var mAPNParameter = mAPN.HasValue ?
                new ObjectParameter("MAPN", mAPN) :
                new ObjectParameter("MAPN", typeof(int));
    
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            var sOLUONGParameter = sOLUONG.HasValue ?
                new ObjectParameter("SOLUONG", sOLUONG) :
                new ObjectParameter("SOLUONG", typeof(int));
    
            var gIANHAPParameter = gIANHAP.HasValue ?
                new ObjectParameter("GIANHAP", gIANHAP) :
                new ObjectParameter("GIANHAP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LapChiTietPhieuNhap", mAPNParameter, mASPParameter, sOLUONGParameter, gIANHAPParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_LapHoaDon(Nullable<int> mAKH, Nullable<int> mANV, Nullable<decimal> tONGTIEN, string gHICHU)
        {
            var mAKHParameter = mAKH.HasValue ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(int));
    
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            var tONGTIENParameter = tONGTIEN.HasValue ?
                new ObjectParameter("TONGTIEN", tONGTIEN) :
                new ObjectParameter("TONGTIEN", typeof(decimal));
    
            var gHICHUParameter = gHICHU != null ?
                new ObjectParameter("GHICHU", gHICHU) :
                new ObjectParameter("GHICHU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_LapHoaDon", mAKHParameter, mANVParameter, tONGTIENParameter, gHICHUParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_LapPhieuNhap(Nullable<int> mANCC, Nullable<int> mANQL, string gHICHU)
        {
            var mANCCParameter = mANCC.HasValue ?
                new ObjectParameter("MANCC", mANCC) :
                new ObjectParameter("MANCC", typeof(int));
    
            var mANQLParameter = mANQL.HasValue ?
                new ObjectParameter("MANQL", mANQL) :
                new ObjectParameter("MANQL", typeof(int));
    
            var gHICHUParameter = gHICHU != null ?
                new ObjectParameter("GHICHU", gHICHU) :
                new ObjectParameter("GHICHU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_LapPhieuNhap", mANCCParameter, mANQLParameter, gHICHUParameter);
        }
    
        public virtual int sp_SuaKhachHang(Nullable<int> mAKH, string tENKH, string gIOITINH, string dIACHI, string dIENTHOAI, string lOAIKH)
        {
            var mAKHParameter = mAKH.HasValue ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(int));
    
            var tENKHParameter = tENKH != null ?
                new ObjectParameter("TENKH", tENKH) :
                new ObjectParameter("TENKH", typeof(string));
    
            var gIOITINHParameter = gIOITINH != null ?
                new ObjectParameter("GIOITINH", gIOITINH) :
                new ObjectParameter("GIOITINH", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var dIENTHOAIParameter = dIENTHOAI != null ?
                new ObjectParameter("DIENTHOAI", dIENTHOAI) :
                new ObjectParameter("DIENTHOAI", typeof(string));
    
            var lOAIKHParameter = lOAIKH != null ?
                new ObjectParameter("LOAIKH", lOAIKH) :
                new ObjectParameter("LOAIKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaKhachHang", mAKHParameter, tENKHParameter, gIOITINHParameter, dIACHIParameter, dIENTHOAIParameter, lOAIKHParameter);
        }
    
        public virtual int sp_SuaMatHang(Nullable<int> mASP, string tENSP, string dVT, Nullable<decimal> gIABAN, string tHONGTIN, string hINHANH, Nullable<int> mATH)
        {
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            var tENSPParameter = tENSP != null ?
                new ObjectParameter("TENSP", tENSP) :
                new ObjectParameter("TENSP", typeof(string));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            var gIABANParameter = gIABAN.HasValue ?
                new ObjectParameter("GIABAN", gIABAN) :
                new ObjectParameter("GIABAN", typeof(decimal));
    
            var tHONGTINParameter = tHONGTIN != null ?
                new ObjectParameter("THONGTIN", tHONGTIN) :
                new ObjectParameter("THONGTIN", typeof(string));
    
            var hINHANHParameter = hINHANH != null ?
                new ObjectParameter("HINHANH", hINHANH) :
                new ObjectParameter("HINHANH", typeof(string));
    
            var mATHParameter = mATH.HasValue ?
                new ObjectParameter("MATH", mATH) :
                new ObjectParameter("MATH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaMatHang", mASPParameter, tENSPParameter, dVTParameter, gIABANParameter, tHONGTINParameter, hINHANHParameter, mATHParameter);
        }
    
        public virtual int sp_SuaNhanVien(Nullable<int> mANV, string tENNV, string gIOITINH, string dIACHI, Nullable<decimal> lUONG, string dIENTHOAI)
        {
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            var tENNVParameter = tENNV != null ?
                new ObjectParameter("TENNV", tENNV) :
                new ObjectParameter("TENNV", typeof(string));
    
            var gIOITINHParameter = gIOITINH != null ?
                new ObjectParameter("GIOITINH", gIOITINH) :
                new ObjectParameter("GIOITINH", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var lUONGParameter = lUONG.HasValue ?
                new ObjectParameter("LUONG", lUONG) :
                new ObjectParameter("LUONG", typeof(decimal));
    
            var dIENTHOAIParameter = dIENTHOAI != null ?
                new ObjectParameter("DIENTHOAI", dIENTHOAI) :
                new ObjectParameter("DIENTHOAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaNhanVien", mANVParameter, tENNVParameter, gIOITINHParameter, dIACHIParameter, lUONGParameter, dIENTHOAIParameter);
        }
    
        public virtual int sp_ThanhToanHoaDon(Nullable<int> mAHD)
        {
            var mAHDParameter = mAHD.HasValue ?
                new ObjectParameter("MAHD", mAHD) :
                new ObjectParameter("MAHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThanhToanHoaDon", mAHDParameter);
        }
    
        public virtual int sp_ThanhToanPhieuNhap(Nullable<int> mAPN)
        {
            var mAPNParameter = mAPN.HasValue ?
                new ObjectParameter("MAPN", mAPN) :
                new ObjectParameter("MAPN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThanhToanPhieuNhap", mAPNParameter);
        }
    
        public virtual int sp_ThemKhachHang(string tENDANGNHAP, string mATKHAU, string tENKH, string gIOITINH, string dIACHI, string dIENTHOAI, string lOAIKH)
        {
            var tENDANGNHAPParameter = tENDANGNHAP != null ?
                new ObjectParameter("TENDANGNHAP", tENDANGNHAP) :
                new ObjectParameter("TENDANGNHAP", typeof(string));
    
            var mATKHAUParameter = mATKHAU != null ?
                new ObjectParameter("MATKHAU", mATKHAU) :
                new ObjectParameter("MATKHAU", typeof(string));
    
            var tENKHParameter = tENKH != null ?
                new ObjectParameter("TENKH", tENKH) :
                new ObjectParameter("TENKH", typeof(string));
    
            var gIOITINHParameter = gIOITINH != null ?
                new ObjectParameter("GIOITINH", gIOITINH) :
                new ObjectParameter("GIOITINH", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var dIENTHOAIParameter = dIENTHOAI != null ?
                new ObjectParameter("DIENTHOAI", dIENTHOAI) :
                new ObjectParameter("DIENTHOAI", typeof(string));
    
            var lOAIKHParameter = lOAIKH != null ?
                new ObjectParameter("LOAIKH", lOAIKH) :
                new ObjectParameter("LOAIKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemKhachHang", tENDANGNHAPParameter, mATKHAUParameter, tENKHParameter, gIOITINHParameter, dIACHIParameter, dIENTHOAIParameter, lOAIKHParameter);
        }
    
        public virtual int sp_ThemMatHang(string tENSP, string dVT, Nullable<decimal> gIABAN, string tHONGTIN, string hINHANH, Nullable<int> mATH)
        {
            var tENSPParameter = tENSP != null ?
                new ObjectParameter("TENSP", tENSP) :
                new ObjectParameter("TENSP", typeof(string));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            var gIABANParameter = gIABAN.HasValue ?
                new ObjectParameter("GIABAN", gIABAN) :
                new ObjectParameter("GIABAN", typeof(decimal));
    
            var tHONGTINParameter = tHONGTIN != null ?
                new ObjectParameter("THONGTIN", tHONGTIN) :
                new ObjectParameter("THONGTIN", typeof(string));
    
            var hINHANHParameter = hINHANH != null ?
                new ObjectParameter("HINHANH", hINHANH) :
                new ObjectParameter("HINHANH", typeof(string));
    
            var mATHParameter = mATH.HasValue ?
                new ObjectParameter("MATH", mATH) :
                new ObjectParameter("MATH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemMatHang", tENSPParameter, dVTParameter, gIABANParameter, tHONGTINParameter, hINHANHParameter, mATHParameter);
        }
    
        public virtual int sp_ThemNhanVien(string tENDANGNHAP, string mATKHAU, string tENNV, string gIOITINH, string dIACHI, Nullable<decimal> lUONG, string dIENTHOAI)
        {
            var tENDANGNHAPParameter = tENDANGNHAP != null ?
                new ObjectParameter("TENDANGNHAP", tENDANGNHAP) :
                new ObjectParameter("TENDANGNHAP", typeof(string));
    
            var mATKHAUParameter = mATKHAU != null ?
                new ObjectParameter("MATKHAU", mATKHAU) :
                new ObjectParameter("MATKHAU", typeof(string));
    
            var tENNVParameter = tENNV != null ?
                new ObjectParameter("TENNV", tENNV) :
                new ObjectParameter("TENNV", typeof(string));
    
            var gIOITINHParameter = gIOITINH != null ?
                new ObjectParameter("GIOITINH", gIOITINH) :
                new ObjectParameter("GIOITINH", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var lUONGParameter = lUONG.HasValue ?
                new ObjectParameter("LUONG", lUONG) :
                new ObjectParameter("LUONG", typeof(decimal));
    
            var dIENTHOAIParameter = dIENTHOAI != null ?
                new ObjectParameter("DIENTHOAI", dIENTHOAI) :
                new ObjectParameter("DIENTHOAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNhanVien", tENDANGNHAPParameter, mATKHAUParameter, tENNVParameter, gIOITINHParameter, dIACHIParameter, lUONGParameter, dIENTHOAIParameter);
        }
    
        public virtual ObjectResult<sp_XemDanhSachKhachHang_Result> sp_XemDanhSachKhachHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XemDanhSachKhachHang_Result>("sp_XemDanhSachKhachHang");
        }
    
        public virtual ObjectResult<sp_XemDanhSachMatHang_Result> sp_XemDanhSachMatHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XemDanhSachMatHang_Result>("sp_XemDanhSachMatHang");
        }
    
        public virtual ObjectResult<sp_XemDanhSachNhanVien_Result> sp_XemDanhSachNhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XemDanhSachNhanVien_Result>("sp_XemDanhSachNhanVien");
        }
    
        public virtual int sp_XoaKhachHang(Nullable<int> mAKH)
        {
            var mAKHParameter = mAKH.HasValue ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaKhachHang", mAKHParameter);
        }
    
        public virtual int sp_XoaMatHang(Nullable<int> mASP)
        {
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaMatHang", mASPParameter);
        }
    
        public virtual int sp_XoaNhanVien(Nullable<int> mANV)
        {
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaNhanVien", mANVParameter);
        }
    
        public virtual int sp_XoaTaiKhoanKhongHoatDong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaTaiKhoanKhongHoatDong");
        }
    }
}
