//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQLCHDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUNHAP()
        {
            this.CHITIETPN = new HashSet<CHITIETPN>();
            this.KHO_SANPHAM = new HashSet<KHO_SANPHAM>();
        }
    
        public int MAPN { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public Nullable<decimal> TIENNHAP { get; set; }
        public string GHICHU { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<int> MANCC { get; set; }
        public Nullable<int> MANQL { get; set; }
    
        public virtual BOPHANKHO BOPHANKHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPN> CHITIETPN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHO_SANPHAM> KHO_SANPHAM { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
